"""
System prompts for the LLM2KG agents.

This module contains all system prompts used in the knowledge graph extraction
and processing pipeline.
"""

from .agent_skb_prompts import (
    KG_EXTRACTION_PROMPT,
    KG_EXTRACTION_PROMPT_MINIMAL,
    KG_EXTRACTION_PROMPT_COMPACT,
    get_extraction_prompt,
    ONTOLOGY_MAPPING_PROMPT_TEMPLATE,
    FROZEN_ONTOLOGY_MAPPING_PROMPT_TEMPLATE,
    LABEL_GENERALIZATION_PROMPT_TEMPLATE,
    ENTITY_VERIFICATION_PROMPT,
    LABEL_VERIFICATION_PROMPT_TEMPLATE,
    ONTOLOGY_MERGE_PROMPT_TEMPLATE,
)

__all__ = [
    "KG_EXTRACTION_PROMPT",
    "KG_EXTRACTION_PROMPT_MINIMAL",
    "KG_EXTRACTION_PROMPT_COMPACT",
    "get_extraction_prompt",
    "ONTOLOGY_MAPPING_PROMPT_TEMPLATE",
    "FROZEN_ONTOLOGY_MAPPING_PROMPT_TEMPLATE",
    "LABEL_GENERALIZATION_PROMPT_TEMPLATE",
    "ENTITY_VERIFICATION_PROMPT",
    "LABEL_VERIFICATION_PROMPT_TEMPLATE",
    "ONTOLOGY_MERGE_PROMPT_TEMPLATE",
]
